name: Linux Test
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ${{ contains(inputs.target, 'aarch64') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Output docker params
        id: docker
        run: |
          node -e "
            if ('${{ inputs.target }}'.startsWith('aarch64')) {
              console.log('PLATFORM=linux/arm64')
            } else if ('${{ inputs.target }}'.startsWith('armv7')) {
              console.log('PLATFORM=linux/arm/v7')
            } else {
              console.log('PLATFORM=linux/amd64')
            }
          " >> $GITHUB_OUTPUT
          node -e "
            if ('${{ inputs.target }}'.endsWith('-musl')) {
              console.log('IMAGE=node:${{ inputs.node-version }}-alpine')
            } else {
              console.log('IMAGE=node:${{ inputs.node-version }}')
            }
          " >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: bun install
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ inputs.target }}
          path: .
      - name: List files
        run: ls -la .
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ contains(inputs.target, 'armv7') }}
        with:
          platforms: all
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        if: ${{ contains(inputs.target, 'armv7') }}
      - name: Test bindings
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ steps.docker.outputs.IMAGE }}
          options: '-v ${{ github.workspace }}:${{ github.workspace }} -w ${{ github.workspace }} --platform ${{ steps.docker.outputs.PLATFORM }}'
          run: |
            if [ -f /usr/bin/apt-get ]; then
              apt-get update && apt-get install -y libx11-6
            fi
            curl -fsSL https://bun.sh/install | bash
            export PATH="$HOME/.bun/bin:$PATH"
            export NAPI_RS_NATIVE_LIBRARY_PATH=$(pwd)/$(ls *.node | head -n 1)
            echo "Using native library: $NAPI_RS_NATIVE_LIBRARY_PATH"
            bun test
